version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - "8080:8080"  # Expose Jenkins UI
      - "50000:50000"  # Agent-to-controller communication port
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-network

  jenkins-agent:
    image: jenkins/jnlp-agent-maven
    container_name: jenkins-agent
    restart: on-failure
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=password
      - JENKINS_AGENT_NAME=agent-1
    networks:
      - jenkins-network

volumes:
  jenkins_home: # Persistent volume for Jenkins data

networks:
  jenkins-network:
    driver: bridge

