---
- name: Install Jenkins master agent tools
  hosts: all
  become: true
  vars:
  tasks:    
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - software-properties-common
          - curl
          - openjdk-17-jdk
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
  

- name: Install Jenkins agent tools
  hosts: 
    - master
    - docker
  become: true
  vars:
  tasks:    
    - name: Add an apt signing key for docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Update cache & Install docker
      ansible.builtin.apt:
        update_cache: yes
        state: present
        pkg:
        - docker-ce
    
    - name: Ensure Docker service is enabled and started
      ansible.builtin.systemd_service:
        state: started
        name: docker    
        enabled: yes

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
- name: Install Jenkins
  hosts: 
    - master
  become: true
  vars:
  tasks:
    - name: docker pull jenkins/jenkins:lts
      ansible.builtin.docker_image:
        name: jenkins/jenkins
        source: pull
        state: present
        force: yes
        pull: yes
        tag: lts
    
    - name: start jenkins container
      ansible.builtin.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/jenkins_home:/var/jenkins_home"
        env:
          JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
          JENKINS_OPTS: "--prefix=/jenkins"
          JENKINS_USER: "{{ ansible_user }}"
          JENKINS_PASS: "{{ ansible_password }}"
          JENKINS_EMAIL: "{{ ansible_user }}@example.com"
          JENKINS_URL: "http://{{ ansible_ssh_host }}:8080"
          JENKINS_SLAVE_AGENT_PORT: "50000"
          JENKINS_HOME: "/var/jenkins_home"
          JENKINS_UC: "https://updates.jenkins.io"
          JENKINS_UC_EXPERIMENTAL: "https://updates.jenkins.io/experimental"
          JENKINS_OPTS: "--httpPort=8080"
          #JENKINS_JAVA_OPTIONS: "-Djenkins.install.runSetupWizard=false