---
- name: Install Containerd, runc, CNI, and Kubernetes
  hosts: all
  become: true
  vars:
    
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - software-properties-common
          - curl
        state: present
        update_cache: yes

    