---
- name: Install Containerd, runc, CNI, and Kubernetes
  hosts: all
  become: true
  vars:
    
  tasks:
    
    - name: Download Jenkins keyring
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      ansible.builtin.copy:
        content: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        dest: /etc/apt/sources.list.d/jenkins.list
    
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - software-properties-common
          - curl
          - openjdk-17-jdk
          - jenkins
        state: present
        update_cache: yes
    
    # - name: Get Jenkins service status
    #   ansible.builtin.systemd:
    #     name: jenkins
    #     state: started
    #   register: jenkins_service_status

    # - name: Display Jenkins service status
    #   ansible.builtin.debug:
    #     msg: >
    #       Jenkins Service Status:
    #       State: {{ jenkins_service_status.state }}

    # - name: Start Jenkins service if inactive
    #   ansible.builtin.systemd:
    #     name: jenkins
    #     state: started
    #   when: jenkins_service_status.state != 'started'

    # - name: start jenins
    #   ansible.builtin.shell: service jenkins start

    - name: Wait for Jenkins to generate the initial admin password
      ansible.builtin.wait_for:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        timeout: 60

    - name: Read the initial admin password
      ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: initial_password
      failed_when: false
        
    - name: Display the initial admin password
      ansible.builtin.debug:
        msg: >
          Jenkins Initial Admin Password \n 
          (Note: This password might have contain new line (/n) unicode character at the end, Please remove it before you use): 
          {{ initial_password.stdout }}

    