#https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html
- name: Playbook to mount ec2
  hosts: all
  remote_user: ubuntu
  become: yes
  gather_facts: true
  tasks:
  - name: ping
    ansible.builtin.ping:
  - name:
    ansible.builtin.gather_facts:
  